:sparkles: feat: Support fractional fps and speed.
Also fix fps computation.

diff --git a/bin/gifify b/bin/gifify
--- a/bin/gifify
+++ b/bin/gifify
@@ -7,14 +7,24 @@
 # and
 # https://github.com/jclem/gifify
 
+function log {
+  >&2 echo "$@"
+}
+
+function debug {
+  if "$verbose" ; then
+    log "$@"
+  fi
+}
+
 function abort {
-  >&2 echo "abort: $1"
+  log "abort: $1"
   exit 1
 }
 
-function show_help ( ) {
-  >&2 echo '! No help for the moment :(' ;
-  >&2 echo ' > Here is the code of the script. The file is located at '"${BASH_SOURCE}".
+function show_help {
+  log '! No help for the moment :(' ;
+  log ' > Here is the code of the script. The file is located at '"${BASH_SOURCE}".
   if command -v bat > /dev/null ; then
     bat "${BASH_SOURCE}"
   elif command -v less > /dev/null ; then
@@ -36,12 +46,12 @@ execute=true       # -p Only parse arguments and print commands.
 
 input=             # -i <input> or gifify [OPTIONS] <input>, defaults to stdin.
 output=            # -o <output>, defaults to stdout.
-fps=10             # -f <fps> ffmpeg -r option.
+fps=10             # -f <fps> frames per second. Accurate up to 3 decimal places.
 resize=            # -r <w:h> ffmpeg scale filter, use -1 when specifying only width or height. `350:100`, `400:-1`, `-1:200`
 
 colors=80          # -c <colors> gifsicle colors option.
 lossy=80           # -z <lossy> gifsicle lossy option.
-delay=             # -d <delay> gifsicle delay option, defaults to automatic := 100 / fps / speed.
+delay=             # -d <delay> gifsicle delay option, defaults to automatic := 100 / fps.
 once=false         # -l gifsicle --no-loopcount flag.
 
 subtitles=         # -s <file> ffmpeg subtitle file.
@@ -54,14 +64,14 @@ duration=          # -D <duration> ffmpeg -t option
 
 crop=              # -C <w:h:x:y> ffmpeg crop filter, default is none.
 reverse=false      # -R ffmpeg reverse filter, default is none.
-speed=1            # -S <speed> used to compute delay when none is given.
-vsync=false        # -V ffmpeg -vsync option, default is none.
+speed=1            # -S <speed> output speedup.
+vsync=             # -V ffmpeg -vsync option, default is none.
 
 gifski=auto        # -g {auto,never,always} when to use gifski, defaults to automatic depending on other arguments.
 fast=false         # -b gifski --fast flag (`b` like butcher).
 quality=           # -q <1-100> gifski --quality option.
 
-while getopts "h?vpi:o:c:z:f:d:r:s:t:lF:T:D:C:RS:Vg:bq:" opt; do
+while getopts "h?vpi:o:c:z:f:d:r:s:t:lF:T:D:C:RS:V:g:bq:" opt; do
     case "$opt" in
     h|\?)
       show_help
@@ -97,13 +107,8 @@ while getopts "h?vpi:o:c:z:f:d:r:s:t:lF:T:D:C:RS:Vg:bq:" opt; do
     D) duration="$OPTARG" ;;
     C) crop="$OPTARG" ;;
     R) reverse=true ;;
-    S)
-      speed="$OPTARG"
-      if [ "$gifski" != "always" ] ; then
-        gifski=never
-      fi
-      ;;
-    V) vsync=true ;;
+    S) speed="$OPTARG" ;;
+    V) vsync="$OPTARG" ;;
     g) gifski="$OPTARG" ;;
     b) fast=true ;;
     q) quality="$OPTARG" ;;
@@ -117,6 +122,7 @@ shift $((OPTIND-1))
 ### PARSING END ###
 
 use_gifski=true
+framerate=
 
 function main {
   checkRequirements
@@ -181,23 +187,29 @@ function interpret {
   if [ "$gifski" = "never" ] ; then
     use_gifski=false
   elif [ "$gifski" = "auto" ] ; then
-    if [ -n "$text" ] || [ -n "$delay" ] ; then
+    if [ -n "$text" ] ; then
       use_gifski=false
     fi
   fi
 
-  if [ -z "$delay" ] ; then
-    tmp1="$(( "$fps" * "$speed" ))"
-    tmp2="$(( 99 + "$tmp1" ))"
-    delay="$(( "$tmp2"  / "$tmp1" ))"
-    delay="$(( 100  / "$tmp1" ))"
+  if ! "$use_gifski" || [ -n "$delay" ] ; then
+    if [ -z "$delay" ] ; then
+      delay="$(calc 0 100 / "$fps")"
+    fi
+    realfps="$(calc 3 100 / "$delay")"
+    if [ "$realfps" != "$fps" ] ; then
+      log "Warning: requesting fps=$fps but can only handle integer delay with gifsicle (floor(100 / "$fps") = "$delay"). Will use fps=$realfps to honor speed=$speed."
+      fps="$realfps"
+    fi
   fi
+
+  framerate="$(calc 0 1000 '*' "$fps")/$(calc 0 1000 '*' "$speed")"
 
 }
 
 function encode {
 
-  >&2 echo "Generating GIF, please wait..."
+  log "Generating GIF, please wait..."
 
   tmpdir="$(mktemp --tmpdir --directory "${USER}-gifify.XXXXXXXX")"
   mkdir -p "$tmpdir/arguments"
@@ -214,9 +226,7 @@ function encode {
 
 function encode_gifski {
 
-  if "$verbose" ; then
-    >&2 echo "Encoding using gifski"
-  fi
+  debug "Encoding using gifski"
 
   mkdir -p "$1/frames"
 
@@ -244,9 +254,7 @@ function encode_gifski {
 
 function encode_default {
 
-  if "$verbose" ; then
-    >&2 echo "Encoding using convert and gifsicle"
-  fi
+  debug "Encoding using convert and gifsicle"
 
   computeFFmpegArgs "$1" > "$1/arguments/ffmpeg"
   computeConvertArgs "$1" > "$1/arguments/convert"
@@ -288,7 +296,7 @@ function computeFFmpegArgs {
     printf '%s\0%s\0' -to "$to"
   fi
 
-  printf '%s\0%s\0' -r "$fps"
+  printf '%s\0%s\0' -r "$framerate"
 
   if [ -n "$resize" ] || [ -n "$subtitles" ] || ( "$reverse" && ! "$use_gifski" ) ; then
     printf '%s\0' -vf
@@ -314,8 +322,8 @@ function computeFFmpegArgs {
 
   # force video sync so that even if nothing moves in the video, we get a constant frame rate
   # seems buggy, not what I want, still, some videos are failing to encode
-  if "$vsync" ; then
-    printf '%s\0%s\0' -vsync 1
+  if [ -n "$vsync" ] ; then
+    printf '%s\0%s\0' -vsync "$vsync"
   fi
 
   if "$use_gifski" ; then
@@ -369,7 +377,7 @@ function computeGifsicleArgs {
 function computeGifskiArgs {
 
   printf '%s\0%s\0'   --output "$output"
-  printf '%s\0%s\0'   --fps "$fps"
+  printf '%s\0%s\0'   --fps "$fps"         # supports fractional fps
   if [ -n "$quality" ] ; then
     printf '%s\0%s\0' --quality "$quality"
   fi
@@ -391,6 +399,20 @@ function computeGifskiArgs {
   fi
 
   find "$1/frames" -type f -print0 | sort -z -n $ordering
+}
+
+function calc {
+  scale="$1" && shift
+  result="$(printf -- "scale=$scale;($*)/1\n" | bc | tr -d '\\\n')"
+  if grep -q '[.]' <<< "$result" ; then
+      # improve the output for decimal numbers
+      printf -- "$result" |
+      sed -e 's/^\./0./'        `# add "0" for cases like ".5"` \
+          -e 's/^-\./-0./'      `# add "0" for cases like "-.5"`\
+          -e 's/0*$//;s/\.$//'   # remove trailing zeros
+  else
+      printf -- "$result"
+  fi
 }
 
 main "$@"
